version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels: [⛓️ Dependencies]
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    labels: [⛓️ Dependencies]
