version: 2

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

changelog:
  use: github-native
