name: 🧰 Bug Report
description: Something doesn't work
labels: ["Type: Bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: ✏️ Describe the Bug
      description: A clear and concise description
      placeholder: |
        - I can't save Login Items with this error message
        - I can't load Login Items correctly
        - mli panics and crashes
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🏭 How to Reproduce the Bug
      description: Steps to reproduce the behavior
      placeholder: |
        Run this command with this `login_items.json`
    validations:
      required: true

  - type: input
    id: mli-version
    attributes:
      label: 📑 mli version
      description: Paste a mli version by `mli -v | pbcopy`
      placeholder: 📑 mli v0.0.0 (#12ab3c4)
    validations:
      required: true

  - type: dropdown
    id: install-method
    attributes:
      label: 📥 How did you install?
      description: Try remember how you started to use it
      multiple: false
      options:
        - Homebrew
        - Go install
        - GitHub Releases
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: ✔︎ Confirm these checks
      description: Make sure you reviewed below
      options:
        - label: I searched the GitHub [Issues](https://github.com/5ouma/mli/issues) or [Discussions](https://github.com/5ouma/mli/discussions).
          required: true
        - label: I tried with the latest version.
          required: false
        - label: I agree to follow the [Code of Conduct](https://github.com/5ouma/mli/blob/main/.github/CODE_OF_CONDUCT.md).
          required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 🗒️ Additional Information
      description: Anything else you want to add
