name: 🚀 Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  tagpr:
    name: 🔖 Release a New Version
    runs-on: Ubuntu-Slim
    environment:
      name: Release
      deployment: false
    timeout-minutes: 1
    outputs:
      tag: ${{ steps.tagpr.outputs.tag }}

    steps:
      - name: 💳 Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true

      - name: 🔖 Release a new version
        id: tagpr
        uses: Songmu/tagpr@9bbb945b2fb025126186661e27d55485e3fc6df6 # v1.18.3
        with:
          config: .github/tagpr.ini
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  release:
    name: 🛠️ Build and Release
    permissions:
      contents: write
    needs: tagpr
    if: ${{ needs.tagpr.outputs.tag != '' }}
    runs-on: Ubuntu-Latest
    timeout-minutes: 2

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 🐹 Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache: false

      - name: 📦 Install dependencies
        run: go mod download

      - name: 🛠️ Build and release
        uses: goreleaser/goreleaser-action@e24998b8b67b290c2fa8b7c14fcfa7de2c5c9b8c # v7.1.0
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
